# Generated by Django 2.2.5 on 2019-09-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserClass',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
